services:

  db:
    image: mysql:latest
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    expose:
      - $DB_DOCKER_PORT

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  node_weaver:
    develop:
      watch:
        - action: sync
          path: ./
          target: /node_weaver
          ignore:
            - node_modules/
    depends_on:
      - db
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=DB
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_ROOT_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  nw_db:
