services:

  db:
    image: mizkyosia/nw-db
    restart: always
    env_file: ./.env
    build: 
      context: ./database
      dockerfile: Dockerfile_db
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    expose:
      - $DB_DOCKER_PORT
    networks:
      - backend
    volumes:
      - nw-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend

  node_weaver:
    image: mizkyosia/nodeweaver
    develop:
      watch:
        - action: sync
          path: ./
          target: /node_weaver
          ignore:
            - node_modules/
    depends_on:
      - db
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=DB
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_ROOT_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_DOCKER_PORT
    stdin_open: true
    tty: true
    networks:
      - backend

volumes:
  nw-db:

networks:
  backend:
    driver: bridge